name: Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  native:
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - beta
          - nightly
        os:
          - macos-15
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install toolchain
        run: rustup toolchain install ${{ matrix.version }} --profile minimal
      - name: Run tests
        run: cargo +${{ matrix.version }} test --verbose

  msrv:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: taiki-e/install-action@cargo-hack
      - name: Run tests
        run: cargo hack test --rust-version --verbose

  cross:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal
      - name: Install cross
        run: cargo +stable install cross --git https://github.com/cross-rs/cross.git --rev 1d07d3f9cc465c435256f1aabc1d18024517891a --locked
      - name: Run tests
        run: cross +stable test --target aarch64-linux-android

  cross-build-only:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-solaris
          - x86_64-unknown-netbsd

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install target
        run: rustup target add ${{ matrix.target }} --toolchain stable
      - name: Build target
        run: cargo +stable build --target ${{ matrix.target }}
